### ISSUE TITLE
Criação de pedido

### ISSUE THREAD

**Issue by v-verner** [mariovalney/shipping-loggi-for-woocommerce#1]
Bom dia,

Instalamos o plugin mas notamos que ele não cria, de fato, o pedido na loggi quando o pedido é aprovado (status processando no woo).  @mariovalney tu tem alguma previsão para implementar essa funcionalidade? Caso não tenha, podemos trabalhar nessa att?

Ah e parabéns pelo trabalho até aqui com o plugin, tá muito bem feito.

**Comment by mariovalney** [comment]
Olá! Tudo bem?
Obrigado pelos parabéns :)

Isso. Ele não cria os pedidos, principalmente por alguns pontos:
- Nossa estimativa de "juntar pacotes" pode divergir um pouco da realidade.
- O lojista pode não querer criar esse pedido na mesma hora, afinal pode precisar de um tempo para entregar.

Existem várias soluções para esses problemas e talvez outros.
Se quiser, podemos discutir sim e ver como seria a melhor forma de criar essa funcionalidade.

**Comment by v-verner** [comment]
Penso que seria bacana deixar isso configurável, tipo, "enviar pedido para o loggi automaticamente" e o admin seta isso e define algum período extra de horários e etc.

Sobre o erro da cotação, isso eu acredito que seja normal porque até no dos correios é alertado como simulação e pode divergir um pouco da realidade. Acredito que de para inserir um "taxa de correção" para o admin definir e isso ser agregado ao valor calculado. O que acha?

Se precisar de uma força para desenvolver, nossa equipe consegue tirar algumas horas durante a semana que vem para implementar essas funcionalidades

**Comment by mariovalney** [comment]
Achei interessante. 
O que acha de uma solução manual na administração?

A gente adicionaria um metabox no pedido para:
- Se: Pedido "Processando" e Entrega "via Loggi" ou há um Pedido Loggi criado.
- Mostra um botão que dispare uma ação.

Outros pontos para pensarmos:
- Salvamos o "pedido" via metadado.
- Mostramos os dados do pedido nessa metabox.

Algumas dúvidas para criar uma história de usuário bacana: o que isso ajuda ao lojista? 
Ele não precisaria entrar na dashboard da Loggi de forma alguma, se integrarmos no WooCommerce?
O que mais ele faria dentro da dashboard durante a operação dele.

**Comment by v-verner** [comment]
Vou separa em tópicos abaixo e depois a gente vê como fica melhor para organizar os requests

- Envio de pedido loggi manual / automatico
Acredito que dá para deixar ambos, por exemplo, o admin define se é para enviar automático quando o pedido entra no status processando ou manual (essa automatização do processo eu vejo como um ponto muito útil para restaurantes e etc. que as vezes não vão ter tempo de ficar vendo o woo direto e corrigindo status)

- MB com os dados da loggi
Acho tri massa isso, eu não cheguei a estudar a fundo a documentação deles, mas provavelmente deve ter alguma consulta por ID da entrega e aí podemos fazer isso via wp_cron ou toda vez que admin abrir o pedido do painel. Com esse histórico automatizado, da até para pensar em automatizar o status para "concluído" quando a loggi retornar como "entregue".

Pessoalmente eu gosto muito de automatizar processos e isso vai reduzir muito o tempo necessário pelo lojista para gerenciar pedidos e isso abre mais tempo para ele cuidar do operacional mesmo do estabelecimento, só temos que separar por prioridade X dificuldade de implementação para também não entregar esses recursos pela metade

**Comment by mariovalney** [comment]
Massa essa tua visão. Obrigado por compartilhar.
(Só a parte de "entregar pela metade" que acho que MVP sempre é válido haha)

Vou tentar um tempinho para fazer pelo menos a parte de criar o pedido.
Mas se quiserem contribuir também é mais do que bem vindo!
(Até porque não sei se a parte do GraphQL tá 100% haha não quis usar biblioteca e fiz uma implementação manual mais para estudo... então não sei se iria complicar a vida de vocês)

O `contributing.md` é um genérico que tenho, mas acho que explica direitinho tudo. Se algo não der certo quando o projeto for montado é só me falar que ajudo. Sigo basicamente o Coding Standard do WP (exceto tabs que não gosto hahah) então o `.editorconfig` e o `precommit` ajudam com o phpcs/phpmd.

Vou criar um roadmap pra nos guiar também.

**Comment by v-verner** [comment]
Boa, combinado, eu tenho outros interessados no plugin também que podem nos ajudar, então vamos mantendo contato! Quando tiver o roadmap pronto, se puder dar um toque, agradeço :D

**Comment by v-verner** [comment]
Boa tarde Mario,

Cara, fizemos um fork do código original apenas para inserir o mvp para geração de pedidos. Modificamos dois arquivos só e deixei a lógica bem simples de enviar para a loggi quando o pedido entra em processando. 

Qualquer dúvida só dar um grito

Link repo `https://github.com/v-verner/shipping-loggi-for-woocommerce`

**Comment by mariovalney** [comment]
Infelizmente a Loggi desativou o Presto.
