### ISSUE TITLE
Peso em kg?

### ISSUE THREAD

**Issue by coreh** [mariovalney/shipping-loggi-for-woocommerce#2]
Boa noite!

Estava investigando por que o método de entrega não aparecia no site, dei uma debugada e percebi que o array de caixas estava vazio...

Fui ler o código que popula as caixas e achei isso:

https://github.com/mariovalney/shipping-loggi-for-woocommerce/blob/master/modules/woocommerce/includes/class-loggi-package.php#L184

É intencional esse `kg`? Removendo ele e deixando somente `g`, as caixas passam a ser populadas corretamente com o peso em gramas do produto, e o método de entrega é exibido normalmente

**Comment by mariovalney** [comment]
É sim. O peso do produto é cadastrado em KG na administração.
As medidas são em CM.

**Comment by mariovalney** [comment]
Notei aqui que é possível que você esteja usando outro valor nas configurações.

Vou remover para manter a função usando o valor que está nas opções do WooCommerce, mas por favor, checa também se está cadastrado corretamente.

**Comment by coreh** [comment]
> Notei aqui que é possível que você esteja usando outro valor nas configurações.

Realmente, conferi aqui: O site está setado para `g`. Não deve ser o mais usual, mas é uma loja que vende alimentos, então deve ter sido para ficar numa escala mais prática. 

Obrigado. Vi sua correção em 5f68c7b1, ficou igual a minha manual. Está funcionando assim para mim. Ele continua funcionando normalmente com o setup em `kg`?

**Comment by mariovalney** [comment]
Sim! Igual às medidas de tamanho.
